Fname =input("enter your frist name :")
Sname=input("enter your second name :")
Tname=input("enter your third name :")
familyname=input("enter your family name :")
print(f"\nFname:{Fname}\nSname:{Sname} \nTname:{Tname} \nfamilyname:{familyname}")